sudo: false
language: node_js
node_js:
  - '9'
cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN
  - export PATH=$HOME/.yarn/bin:$PATH
install: yarn install
before_script: yarn --cwd stories install
script: yarn validate
after_success: kcd-scripts travis-after-success
branches:
  only: master
